services:
  app:
    container_name: farma-server-deploy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bash -c "npm run start:dev"